### ISSUE TITLE
Can no longer access icann artifactory

### ISSUE THREAD

**Issue by mckeckers** [icann/rdap-conformance-tool#10]
As of 09/03/2022, the ICANN repository https://artifactory.icann.org/artifactory/ICANN-repository is no longer accessible.

Prior to this date I was able to download the required dependencies.  If this repo should not be accessible to external users, please can the dependencies be published to maven central.

**Comment by e-alvarez** [comment]
Thank you for your feedback. We will look into removing this dependency from ICANN's repository.

**Comment by e-alvarez** [comment]
We have now removed the dependency on ICANN's repository from the project. Library dependencies will be retrieved now from maven central when building the project. Please let us know should you continue to experience any issues.
